version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.12.2   # Specify the Python version you want to use

    steps:
      - checkout  # Check out the code from the repository

      - run:
          name: Set up virtual environment and install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip  # Ensure pip is up-to-date
            pip install -r requirements.txt

      - run:
          name: Verify pytest installation
          command: |
            . venv/bin/activate
            pip show pytest

      - run:
          name: Run tests with pytest
          command: |
            . venv/bin/activate
            pytest

  deploy:
    # This is an example deploy job, not actually used by the workflow
    docker:
      - image: cimg/base:stable
    steps:
      # Replace this with steps to deploy to users
      - run:
          name: deploy
          command: '#e.g. ./deploy.sh'

workflows:
  build-and-test:
    jobs:
      - test
    # - deploy:
    #     requires:
    #       - test

    # - deploy:
    #     requires:
    #       - test-python
